version: "3"
services:
  registry:
    image: registry:2
    container_name: registry
    volumes:
      - ./docker-registry/conf/config.yml:/etc/docker/registry/config.yml
      - ./docker-registry/auth:/auth
      - ./docker-registry/data/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      - registry
    restart: always

    
networks:
  registry:
    driver: bridge