version: '3.1' #版本号
services: 
  nginx:
    restart: always 
    image: nginx:latest
    container_name: nginx 
    ports:
      - 8090:80 
      - 443:443
    volumes:  #数据卷映射地址
      - ./conf.d/:/etc/nginx/conf.d/