version: '3.1'
services: 
  nginx:
    restart: always 
    image: jira-software-with-proxy:8.15.1
    container_name: jira
    ports:
      - 8080:8080 
    volumes:  #数据卷映射地址
      - ./data:/var/jira
      - ./agent:/agent
    environment:
      - TZ=Asia/Shanghai
    # - JVM_MINIMUM_MEMORY=1g
    # - JVM_MAXIMUM_MEMORY=4G
    # - ATL_PROXY_NAME=jira.example.com
    # - ATL_PROXY_PORT=443
    # - ATL_TOMCAT_SCHEME=https
    # - ATL_TOMCAT_SECURE=true