version: '3'

services:
  neo4j:
    image: "neo4j:3.5.25"
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data:/data"
      - "./logs:/logs"
      - "./conf:/var/lib/neo4j/conf"
      - "./import:/var/lib/neo4j/import"
    environment:
      - NEO4J_AUTH=neo4j/changeme