version: '3'
services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper/data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: kafka:3.2
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "./kafka/data:/bitnami"
      - "/etc/localtime:/etc/localtime"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      # - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9092
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # - KAFKA_CLIENT_USERS=user
      # - KAFKA_CLIENT_PASSWORDS=password
    depends_on:
      - zookeeper