version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server:21.3.16.5
    restart: always
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9009:9009
      - 9090:9090
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes: 
      # 默认配置 写入config.d/users.d 目录防止更新后文件丢失
      - ./config.xml:/etc/clickhouse-server/config.d/config.xml:rw
      - ./users.xml:/etc/clickhouse-server/users.xml:rw
      # 运行日志
      - ./logs:/var/log/clickhouse-server
      # 数据持久
      - ./data:/var/lib/clickhouse:rw