version: '3'

services:
  minio:
    image: minio:2022.9.17
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=changeme

volumes:
  data:
    driver: local