version: "3"
services:
  mongo:
    # image: mongo:6.0.2
    image: mongo:6.0.2
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db