version: '3'
services:
  nginx:
    restart: always 
    image: nginx:latest
    container_name: nginx 
    ports:
      - 8090:80 
    volumes: 
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/download:/usr/share/nginx/html:ro